//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education_detail
    {
        public int Education_detail_id { get; set; }
        public int Employee_ID { get; set; }
        public string Education { get; set; }
        public string University { get; set; }
        public string Grade_Obtained { get; set; }
        public string Passing_Year { get; set; }
        public bool Active_status { get; set; }
    
        public virtual Employee_master Employee_master { get; set; }
    }
}
