//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeDatabaseEntities1 : DbContext
    {
        public EmployeeDatabaseEntities1()
            : base("name=EmployeeDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education_detail> Education_detail { get; set; }
        public virtual DbSet<Employee_master> Employee_master { get; set; }
        public virtual DbSet<tbl_User_Table> tbl_User_Table { get; set; }
        public virtual DbSet<tbl_Error_Log> tbl_Error_Log { get; set; }
    
        public virtual int proc_employee_master_save(string employee_Name, string contact_No, string email, string address1, string address2, string city, string state, string country, string zipcode)
        {
            var employee_NameParameter = employee_Name != null ?
                new ObjectParameter("Employee_Name", employee_Name) :
                new ObjectParameter("Employee_Name", typeof(string));
    
            var contact_NoParameter = contact_No != null ?
                new ObjectParameter("Contact_No", contact_No) :
                new ObjectParameter("Contact_No", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_employee_master_save", employee_NameParameter, contact_NoParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, countryParameter, zipcodeParameter);
        }
    
        public virtual ObjectResult<proc_employee_master_select_all_Result> proc_employee_master_select_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_employee_master_select_all_Result>("proc_employee_master_select_all");
        }
    
        public virtual ObjectResult<proc_employee_master_select_by_id_Result> proc_employee_master_select_by_id(Nullable<int> employee_id)
        {
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("Employee_id", employee_id) :
                new ObjectParameter("Employee_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_employee_master_select_by_id_Result>("proc_employee_master_select_by_id", employee_idParameter);
        }
    
        public virtual int proc_employee_master_update(Nullable<int> employee_ID, string employee_Name, string contact_No, string email, string address1, string address2, string city, string state, string country, string zipcode)
        {
            var employee_IDParameter = employee_ID.HasValue ?
                new ObjectParameter("Employee_ID", employee_ID) :
                new ObjectParameter("Employee_ID", typeof(int));
    
            var employee_NameParameter = employee_Name != null ?
                new ObjectParameter("Employee_Name", employee_Name) :
                new ObjectParameter("Employee_Name", typeof(string));
    
            var contact_NoParameter = contact_No != null ?
                new ObjectParameter("Contact_No", contact_No) :
                new ObjectParameter("Contact_No", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_employee_master_update", employee_IDParameter, employee_NameParameter, contact_NoParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, countryParameter, zipcodeParameter);
        }
    
        public virtual int proc_employee_master_update_status(Nullable<int> employee_ID, Nullable<bool> status)
        {
            var employee_IDParameter = employee_ID.HasValue ?
                new ObjectParameter("Employee_ID", employee_ID) :
                new ObjectParameter("Employee_ID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_employee_master_update_status", employee_IDParameter, statusParameter);
        }
    }
}
